/**
 * The press-box gallery, listed explicitly.
 *
 * This used to be generated by counting 1 to 54 and padding the number,
 * which assumed an unbroken sequence. It is not one: 001, 004, 010, 012
 * and 019 do not exist, so the About page rendered five broken images with
 * their alt text showing. Generating paths for files that might not be
 * there will always fail silently, so the list is now literal.
 *
 * This module is imported by client components, so it cannot read the
 * directory at runtime. When photographs are added or removed, update this
 * array. `npm run build` will not catch a missing file for you.
 */
const galleryImages = [
  "/images/gallery/cuva-sports-002.jpg",
  "/images/gallery/cuva-sports-003.jpg",
  "/images/gallery/cuva-sports-005.jpg",
  "/images/gallery/cuva-sports-006.jpg",
  "/images/gallery/cuva-sports-007.jpg",
  "/images/gallery/cuva-sports-008.jpg",
  "/images/gallery/cuva-sports-009.jpg",
  "/images/gallery/cuva-sports-011.jpg",
  "/images/gallery/cuva-sports-013.jpg",
  "/images/gallery/cuva-sports-014.jpg",
  "/images/gallery/cuva-sports-015.jpg",
  "/images/gallery/cuva-sports-016.jpg",
  "/images/gallery/cuva-sports-017.jpg",
  "/images/gallery/cuva-sports-018.jpg",
  "/images/gallery/cuva-sports-020.jpg",
  "/images/gallery/cuva-sports-021.jpg",
  "/images/gallery/cuva-sports-022.jpg",
  "/images/gallery/cuva-sports-023.jpg",
  "/images/gallery/cuva-sports-024.jpg",
  "/images/gallery/cuva-sports-025.jpg",
  "/images/gallery/cuva-sports-026.jpg",
  "/images/gallery/cuva-sports-027.jpg",
  "/images/gallery/cuva-sports-028.jpg",
  "/images/gallery/cuva-sports-029.jpg",
  "/images/gallery/cuva-sports-030.jpg",
  "/images/gallery/cuva-sports-031.jpg",
  "/images/gallery/cuva-sports-032.jpg",
  "/images/gallery/cuva-sports-033.jpg",
  "/images/gallery/cuva-sports-034.jpg",
  "/images/gallery/cuva-sports-035.jpg",
  "/images/gallery/cuva-sports-036.jpg",
  "/images/gallery/cuva-sports-037.jpg",
  "/images/gallery/cuva-sports-038.jpg",
  "/images/gallery/cuva-sports-039.jpg",
  "/images/gallery/cuva-sports-040.jpg",
  "/images/gallery/cuva-sports-041.jpg",
  "/images/gallery/cuva-sports-042.jpg",
  "/images/gallery/cuva-sports-043.jpg",
  "/images/gallery/cuva-sports-044.jpg",
  "/images/gallery/cuva-sports-045.jpg",
  "/images/gallery/cuva-sports-046.jpg",
  "/images/gallery/cuva-sports-047.jpg",
  "/images/gallery/cuva-sports-048.jpg",
  "/images/gallery/cuva-sports-049.jpg",
  "/images/gallery/cuva-sports-050.jpg",
  "/images/gallery/cuva-sports-051.jpg",
  "/images/gallery/cuva-sports-052.jpg",
  "/images/gallery/cuva-sports-053.jpg",
  "/images/gallery/cuva-sports-054.jpg",
];

const categoryFallbacks: Record<string, string> = {
  football: "/images/fallback-football.jpg",
  cricket: "/images/fallback-cricket.jpg",
};

/**
 * Returns the article's own image, or `undefined` when it has none. Cards pass
 * the result to <MatchCardImage/>, which renders the branded
 * <MatchReportFallback/> UI in place of a stock/Lincoln fallback photo.
 */
export function getImageForArticle(
  slug: string,
  category: string,
  articleImage?: string
): string | undefined {
  return articleImage || undefined;
}

export function getCategoryFallback(category: string): string {
  return categoryFallbacks[category] || categoryFallbacks.football;
}

export { galleryImages };
